_target_: torchvision.transforms.Compose
transforms:
  - _target_: torchvision.transforms.v2.RandomApply
    transforms: 
      - _target_: torchvision.transforms.v2.RandomCrop
        size: [150, 150]
  - _target_: torchvision.transforms.v2.RandomHorizontalFlip
    p: 0.5
  - _target_: torchvision.transforms.v2.RandomRotation
    degrees: 45
  - _target_: torchvision.transforms.v2.RandomGrayscale
    p: 0.1
  - _target_: torchvision.transforms.Resize
    size: [224, 224]
  - _target_: torchvision.transforms.ToTensor
  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
