defaults:
  - train_transform: randaug
  - test_transform: simple

name: multi_situation_refined
num_classes: 37
batch_size: 128
num_workers: 8
train_path: ${data_dir}/train/finetuned/all_epochs_1
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
